// directus/extensions/imobi-crm/src/routes/leads.vue
<template>
  <div class="leads">
    <v-info v-if="!companyId" type="warning" icon="business" title="Nenhuma empresa selecionada">
      Selecione uma empresa no menu superior.
    </v-info>

    <template v-else>
      <div class="toolbar">
        <v-input
          v-model="search"
          placeholder="Buscar por nome, email ou telefone"
          icon-left="search"
          :disabled="loading"
        />
        <v-button icon="refresh" :loading="loading" @click="loadLeads">Atualizar</v-button>
      </div>

      <div class="stats-grid">
        <v-card v-for="card in statsCards" :key="card.label">
          <v-card-title>
            <v-icon :name="card.icon" left />
            {{ card.label }}
          </v-card-title>
          <v-card-text class="stat-value">
            {{ card.value }}
          </v-card-text>
        </v-card>
      </div>

      <v-alert v-if="error" type="danger" icon="error" class="mb-4">
        {{ error }}
      </v-alert>

      <v-progress-linear v-if="loading" indeterminate class="mb-4" />

      <div class="board" v-else>
        <div v-for="stage in stages" :key="stage.id" class="column">
          <div class="column-header">
            <div>
              <p class="column-title">{{ stage.label }}</p>
              <small>{{ stageLeads(stage.id).length }} lead(s)</small>
            </div>
            <v-chip small :style="{ background: stage.badge, color: '#fff' }">
              {{ stage.short }}
            </v-chip>
          </div>

          <div class="column-body">
            <div v-if="stageLeads(stage.id).length === 0" class="empty-card">
              <v-icon name="inbox" class="mb-2" />
              <p>Nenhum lead neste estágio</p>
            </div>

            <v-card v-for="lead in stageLeads(stage.id)" :key="lead.id" class="lead-card">
              <div class="lead-header">
                <div>
                  <strong>{{ lead.name || 'Sem nome' }}</strong>
                  <p class="muted">{{ formatDate(lead.created_at) }}</p>
                </div>
                <span class="interest" :style="{ background: stage.badge }">
                  {{ interestLabel(lead.interest_type) }}
                </span>
              </div>

              <div class="lead-info">
                <div class="info-row">
                  <v-icon name="mail" small />
                  <span>{{ lead.email || 'Sem email' }}</span>
                </div>
                <div class="info-row">
                  <v-icon name="phone" small />
                  <span>{{ formatPhone(lead.phone || '') }}</span>
                </div>
                <div class="info-row" v-if="lead.budget_min || lead.budget_max">
                  <v-icon name="attach_money" small />
                  <span>{{ formatBudget(lead.budget_min, lead.budget_max) }}</span>
                </div>
              </div>

              <div class="lead-actions">
                <v-select
                  :model-value="lead.stage"
                  :items="stageOptions"
                  :disabled="updating === lead.id"
                  placeholder="Alterar estágio"
                  @update:modelValue="(value) => updateStage(lead.id, value as string)"
                />
                <div class="action-buttons">
                  <v-button
                    icon="whatsapp"
                    :title="'Conversar com ' + (lead.name || 'lead')"
                    :href="buildWhatsAppUrl(lead.phone)"
                    target="_blank"
                    rel="noopener"
                    secondary
                  />
                  <router-link :to="`/content/leads/${lead.id}`" class="details-link">Ver registro</router-link>
                </div>
              </div>
            </v-card>
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useApi } from '@directus/extensions-sdk';

type Lead = {
  id: string;
  name: string | null;
  email: string | null;
  phone: string | null;
  interest_type: string | null;
  budget_min?: number | null;
  budget_max?: number | null;
  stage: string;
  created_at: string;
};

const props = defineProps<{
  companyId: string | null;
}>();

const api = useApi();
const leads = ref<Lead[]>([]);
const loading = ref(false);
const error = ref('');
const search = ref('');
const updating = ref<string | null>(null);

const stages = [
  { id: 'new', label: 'Novo', short: 'N', badge: '#2563eb' },
  { id: 'contacted', label: 'Contatado', short: 'C', badge: '#7c3aed' },
  { id: 'qualified', label: 'Qualificado', short: 'Q', badge: '#c2410c' },
  { id: 'visit_scheduled', label: 'Visita', short: 'V', badge: '#ea580c' },
  { id: 'negotiating', label: 'Negociando', short: 'Neg', badge: '#0ea5e9' },
  { id: 'won', label: 'Fechado', short: 'F', badge: '#16a34a' },
  { id: 'lost', label: 'Perdido', short: 'P', badge: '#6b7280' },
];

const stageOptions = stages.map((stage) => ({ label: stage.label, value: stage.id }));

const filteredLeads = computed(() => {
  if (!search.value) return leads.value;
  const term = search.value.toLowerCase();
  return leads.value.filter((lead) => [lead.name, lead.email, lead.phone]
    .filter(Boolean)
    .some((field) => field!.toLowerCase().includes(term)));
});

const statsCards = computed(() => [
  { label: 'Total', icon: 'people', value: leads.value.length },
  { label: 'Novos', icon: 'bolt', value: stageLeads('new').length },
  { label: 'Em contato', icon: 'chat', value: stageLeads('contacted').length },
  { label: 'Fechados', icon: 'check_circle', value: stageLeads('won').length },
]);

function stageLeads(stageId: string) {
  return filteredLeads.value.filter((lead) => lead.stage === stageId);
}

function interestLabel(type: string | null) {
  if (!type) return '—';
  const labels: Record<string, string> = {
    buy: 'Compra',
    rent: 'Aluguel',
  };
  return labels[type] || type;
}

function formatPhone(phone: string) {
  const digits = phone.replace(/\D/g, '');
  if (digits.length === 11) {
    return `(${digits.slice(0, 2)}) ${digits.slice(2, 7)}-${digits.slice(7)}`;
  }
  if (digits.length === 10) {
    return `(${digits.slice(0, 2)}) ${digits.slice(2, 6)}-${digits.slice(6)}`;
  }
  return phone || 'Sem telefone';
}

function formatBudget(min?: number | null, max?: number | null) {
  if (!min && !max) return 'Sem orçamento';
  const formatter = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
  if (min && max) {
    return `${formatter.format(min)} - ${formatter.format(max)}`;
  }
  return formatter.format(min || max || 0);
}

function formatDate(dateString: string) {
  return new Date(dateString).toLocaleDateString('pt-BR', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  });
}

function buildWhatsAppUrl(phone: string | null) {
  if (!phone) return undefined;
  const digits = phone.replace(/\D/g, '');
  if (!digits) return undefined;
  const message = encodeURIComponent('Olá! Recebemos seu contato pelo site iMOBI.');
  return `https://wa.me/${digits}?text=${message}`;
}

async function loadLeads() {
  if (!props.companyId) return;
  loading.value = true;
  error.value = '';

  try {
    const response = await api.get('/items/leads', {
      params: {
        filter: { company_id: { _eq: props.companyId } },
        sort: ['-created_at'],
        fields: [
          'id',
          'name',
          'email',
          'phone',
          'interest_type',
          'budget_min',
          'budget_max',
          'stage',
          'created_at',
        ],
      },
    });

    leads.value = response.data.data || [];
  } catch (err) {
    console.error('Erro ao carregar leads:', err);
    error.value = 'Não foi possível carregar os leads. Tente novamente.';
  } finally {
    loading.value = false;
  }
}

async function updateStage(leadId: string, stage: string) {
  if (updating.value) return;
  updating.value = leadId;

  try {
    await api.patch(`/items/leads/${leadId}`, { stage });
    const lead = leads.value.find((item) => item.id === leadId);
    if (lead) lead.stage = stage;
  } catch (err) {
    console.error('Erro ao atualizar estágio:', err);
    error.value = 'Não foi possível alterar o estágio do lead.';
  } finally {
    updating.value = null;
  }
}

watch(
  () => props.companyId,
  (value) => {
    if (value) {
      loadLeads();
    } else {
      leads.value = [];
    }
  },
  { immediate: true }
);
</script>

<style scoped>
.leads {
  padding: var(--content-padding);
  padding-top: var(--content-padding-bottom);
}

.toolbar {
  display: flex;
  gap: 12px;
  align-items: center;
  margin-bottom: 20px;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  gap: 16px;
  margin-bottom: 24px;
}

.stat-value {
  font-size: 2rem;
  font-weight: 700;
}

.board {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
  gap: 16px;
}

.column {
  background: var(--theme--background-subdued);
  border-radius: var(--theme--border-radius);
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.column-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.column-title {
  font-weight: 600;
  margin-bottom: 2px;
}

.column-body {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.empty-card {
  background: var(--theme--background);
  border: 1px dashed var(--theme--border-color-subdued);
  border-radius: var(--theme--border-radius);
  padding: 20px;
  text-align: center;
  color: var(--theme--foreground-subdued);
}

.lead-card {
  background: var(--theme--background);
}

.lead-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 12px;
}

.muted {
  color: var(--theme--foreground-subdued);
  font-size: 0.85rem;
}

.interest {
  padding: 4px 8px;
  border-radius: 999px;
  color: #fff;
  font-size: 0.75rem;
  font-weight: 600;
}

.lead-info {
  margin: 12px 0;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.info-row {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 0.9rem;
}

.lead-actions {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.action-buttons {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 12px;
}

.details-link {
  font-weight: 600;
  color: var(--theme--primary);
}

@media (max-width: 768px) {
  .toolbar {
    flex-direction: column;
    align-items: stretch;
  }

  .action-buttons {
    flex-direction: column;
    align-items: stretch;
  }
}
</style>

// nextjs/src/app/empresa/leads/page.tsx
import { directusServer } from '@/lib/directus/client';
import { readItems, aggregate } from '@directus/sdk';
import { getAuthenticatedCompanyId } from '@/lib/auth/server';
import Link from 'next/link';

async function getCompanyLeads(companyId: string) {
  try {
    // @ts-ignore - Custom schema
    
    return await directusServer.request(
      readItems('leads', {
        filter: {
          company_id: { _eq: companyId }
        },
        // @ts-ignore
        sort: ['-created_at'],
        fields: ['*']
      })
    );
  } catch (error) {
    console.error('Error fetching leads:', error);
    
    return [];
  }
}

async function getLeadsStats(companyId: string) {
  try {
    // @ts-ignore - Custom schema
    const total = await directusServer.request(
      aggregate('leads', {
        aggregate: { count: '*' },
        query: {
          filter: { company_id: { _eq: companyId } }
        }
      })
    );

    // @ts-ignore
    const newLeads = await directusServer.request(
      aggregate('leads', {
        aggregate: { count: '*' },
        query: {
          filter: {
            company_id: { _eq: companyId },
            stage: { _eq: 'new' }
          }
        }
      })
    );

    // @ts-ignore
    const contacted = await directusServer.request(
      aggregate('leads', {
        aggregate: { count: '*' },
        query: {
          filter: {
            company_id: { _eq: companyId },
            stage: { _eq: 'contacted' }
          }
        }
      })
    );

    // @ts-ignore
    const won = await directusServer.request(
      aggregate('leads', {
        aggregate: { count: '*' },
        query: {
          filter: {
            company_id: { _eq: companyId },
            stage: { _eq: 'won' }
          }
        }
      })
    );

    
    return {
      total: Number(total[0]?.count || 0),
      new: Number(newLeads[0]?.count || 0),
      contacted: Number(contacted[0]?.count || 0),
      won: Number(won[0]?.count || 0)
    };
  } catch (error) {
    console.error('Error fetching leads stats:', error);
    
    return { total: 0, new: 0, contacted: 0, won: 0 };
  }
}

function getStageLabel(stage: string): string {
  const stages: Record<string, string> = {
    new: 'Novo',
    contacted: 'Contatado',
    qualified: 'Qualificado',
    visit_scheduled: 'Visita Agendada',
    negotiating: 'Negociando',
    won: 'Fechado',
    lost: 'Perdido'
  };

  return stages[stage] || stage;
}

function getStageColor(stage: string): string {
  const colors: Record<string, string> = {
    new: 'bg-blue-100 text-blue-800',
    contacted: 'bg-purple-100 text-purple-800',
    qualified: 'bg-yellow-100 text-yellow-800',
    visit_scheduled: 'bg-orange-100 text-orange-800',
    negotiating: 'bg-indigo-100 text-indigo-800',
    won: 'bg-green-100 text-green-800',
    lost: 'bg-gray-100 text-gray-800'
  };

  return colors[stage] || 'bg-gray-100 text-gray-800';
}

function getInterestTypeLabel(type: string): string {
  const types: Record<string, string> = {
    buy: 'Compra',
    rent: 'Aluguel'
  };

  return types[type] || type;
}

function formatDate(dateString: string): string {
  const date = new Date(dateString);

  return date.toLocaleDateString('pt-BR', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric'
  });
}

function formatPhone(phone: string): string {
  // Remove all non-digits
  const cleaned = phone.replace(/\D/g, '');
  
  // Format based on length
  if (cleaned.length === 11) {
    return `(${cleaned.slice(0, 2)}) ${cleaned.slice(2, 7)}-${cleaned.slice(7)}`;
  } else if (cleaned.length === 10) {
    return `(${cleaned.slice(0, 2)}) ${cleaned.slice(2, 6)}-${cleaned.slice(6)}`;
  }


  return phone;
}

export default async function LeadsPage() {
  const companyId = await getAuthenticatedCompanyId();
  
  const leads = await getCompanyLeads(companyId);
  const stats = await getLeadsStats(companyId);

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b">
        <div className="container mx-auto px-4 py-6">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold mb-2">Gerenciar Leads</h1>
              <p className="text-gray-600">
                Acompanhe e gerencie seus potenciais clientes
              </p>
            </div>
            <Link
              href="/empresa/dashboard"
              className="bg-gray-600 hover:bg-gray-700 text-white px-6 py-3 rounded-md font-semibold transition-colors"
            >
              ← Voltar ao Dashboard
            </Link>
          </div>
        </div>
      </div>

      <div className="container mx-auto px-4 py-8">
        {/* Stats Cards */}
        <div className="grid gap-4 md:grid-cols-4 mb-8">
          <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Total</p>
                <p className="text-3xl font-bold text-gray-900">{stats.total}</p>
              </div>
              <div className="bg-blue-100 rounded-full p-3">
                <svg className="h-6 w-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                </svg>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Novos</p>
                <p className="text-3xl font-bold text-blue-900">{stats.new}</p>
              </div>
              <div className="bg-blue-50 rounded-full p-3">
                <svg className="h-6 w-6 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                </svg>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Em Contato</p>
                <p className="text-3xl font-bold text-purple-900">{stats.contacted}</p>
              </div>
              <div className="bg-purple-50 rounded-full p-3">
                <svg className="h-6 w-6 text-purple-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
                </svg>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-lg shadow p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Fechados</p>
                <p className="text-3xl font-bold text-green-900">{stats.won}</p>
              </div>
              <div className="bg-green-50 rounded-full p-3">
                <svg className="h-6 w-6 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
            </div>
          </div>
        </div>

        {/* Leads Table */}
        <div className="bg-white rounded-lg shadow overflow-hidden">
          <div className="px-6 py-4 border-b border-gray-200">
            <h2 className="text-xl font-semibold">Todos os Leads</h2>
          </div>

          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Nome
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Contato
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Interesse
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Orçamento
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Status
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Data
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Ações
                  </th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {leads.length === 0 ? (
                  <tr>
                    <td colSpan={7} className="px-6 py-12 text-center text-gray-500">
                      <div className="flex flex-col items-center">
                        <svg className="h-12 w-12 text-gray-400 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                        </svg>
                        <p className="text-lg font-medium">Nenhum lead ainda</p>
                        <p className="text-sm">Quando alguém entrar em contato, aparecerá aqui</p>
                      </div>
                    </td>
                  </tr>
                ) : (
                  leads.map((lead: any) => (
                    <tr key={lead.id} className="hover:bg-gray-50">
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm font-medium text-gray-900">{lead.name}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm text-gray-900">{lead.email}</div>
                        <div className="text-sm text-gray-500">{formatPhone(lead.phone)}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className="text-sm text-gray-900">
                          {getInterestTypeLabel(lead.interest_type)}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        {lead.budget_min && lead.budget_max ? (
                          <div className="text-sm text-gray-900">
                            R$ {lead.budget_min?.toLocaleString('pt-BR')} - {lead.budget_max?.toLocaleString('pt-BR')}
                          </div>
                        ) : (
                          <span className="text-sm text-gray-400">-</span>
                        )}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${getStageColor(lead.stage)}`}>
                          {getStageLabel(lead.stage)}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {formatDate(lead.created_at)}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <Link
                          href={`/empresa/leads/${lead.id}`}
                          className="text-blue-600 hover:text-blue-900 mr-4"
                        >
                          Ver Detalhes
                        </Link>
                        <a
                          href={`https://wa.me/${lead.phone.replace(/\D/g, '')}`}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-green-600 hover:text-green-900"
                        >
                          WhatsApp
                        </a>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
